apiVersion: v1
name: s3-chart
description: A Helm chart for the ACK service controller for Amazon Simple Storage Service (S3)
version: 1.0.6
appVersion: 1.0.6
home: https://github.com/aws-controllers-k8s/s3-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/s3-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: S3 Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/s3-maintainer
keywords:
  - aws
  - kubernetes
  - s3
